# Generated by Django 3.1.4 on 2020-12-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Contraseña', models.CharField(max_length=50)),
                ('Rol', models.CharField(max_length=50)),
                ('Estado', models.BooleanField()),
            ],
        ),
    ]
